# 服务统一8500
spring:
  application:
    name: serviceOne
eureka:
  client:
    serviceUrl:
      defaultZone: http://gxj-master:8000/eureka/,http://wpj-slave1:8001/eureka/,http://wpj-slave2:8002/eureka/  #注册中心地址
  instance:
    hostname: gxj-master
    instance-id: http://gxj-master:8400
server:
  port: 8400
