# 注册中心统一8000开头
spring:
  profiles:
    active: master
---
spring:
  profiles: master
  application:
    name: eurekas
server:
  port: 8000 # 注册中心占用8080端口
eureka:
  instance:
    hostname: gxj-master
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/,http://${eureka.instance.hostname}:8002/eureka/
---
spring:
  profiles: slave1
  application:
      name: eurekas
server:
  port: 8001
eureka:
  instance:
    hostname: wpj-slave1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/,http://${eureka.instance.hostname}:8002/eureka/
---
spring:
  profiles: slave2
  application:
      name: eurekas
eureka:
  instance:
    hostname: wpj-slave2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/,http://${eureka.instance.hostname}:8001/eureka/
server:
  port: 8002