# 网关统一8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://gxj-master:8000/eureka/,http://wpj-slave1:8001/eureka/,http://wpj-slave2:8002/eureka/
spring:
  application:
    name: gateway
server:
  port: 8100
zuul:
  routes:
    serviceOne:
       path: /service/0/**
       serviceId: ribbonConsumer
    serviceTwo:
       path: /service/1/**
       serviceId: feign
