eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    serviceOne:
       path: /service/0/**
       serviceId: ribbonConsumer
    serviceTwo:
       path: /service/1/**
       serviceId: feign
