spring:
  application:
    name: feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:9090/eureka/,http://localhost:10101/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8084
server:
  port: 8085
## 必须添加对hystrix的支持否无法回调函数fallback函数无法生效
feign:
  hystrix:
    enabled: true
