##/{application}/{profile}[/{label}]
## /{application}-{profile}.yml
## /{label}/{application}-{profile}.yml
## /{application}-{profile}.properties
## /{label}/{application}-{profile}.properties
server:
  port: 8600
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BigDuck/spring-cloud-demo
          search-paths: config-resp
  application:
    name: configServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://gxj-master:8000/eureka/,http://wpj-slave1:8001/eureka/,http://wpj-slave2:8002/eureka/  #注册中心地址
