##/{application}/{profile}[/{label}]
## /{application}-{profile}.yml
## /{label}/{application}-{profile}.yml
## /{application}-{profile}.properties
## /{label}/{application}-{profile}.properties
# http://localhost:8600/db/dev/master
server:
  port: 8600
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BigDuck/spring-cloud-demo
          search-paths: config-resp
  application:
    name: configServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://gxj-master:8000/eureka/,http://wpj-slave1:8001/eureka/,http://wpj-slave2:8002/eureka/ #注册中心地址
encrypt:
  key-store:
    location: config-server.keystore
    alias: config-server
    password: 757671834
    secret: 757671834
# keytool -genkeypair -alias config-server -keyalg RSA -keystore config-server.keystore 然后根据提示生成密钥
## http://localhost:8600/decrypt 解密
## http://localhost:8600/encrypt 加密