spring:
  application:
    name: serviceTwo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8082
server:
  port: 8082 #servic占用8082
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000  # feign 超时控制
serviceTwo:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 500
    MaxAutoRetries: 1  # SR6版本,这里设为1,会重试3次,重试次数还和另外的两个值有关

